SELECT MONTH, CAR_ID, RECORDS
FROM (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS,
            SUM(COUNT(CAR_ID)) OVER(PARTITION BY CAR_ID) AS SUMRECORDS
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE DATE_FORMAT(START_DATE, "%m") BETWEEN 8 AND 10
      GROUP BY MONTH, CAR_ID
      ORDER BY MONTH, CAR_ID DESC ) A
WHERE SUMRECORDS >= 5